[package]
name = "bevy_app"
version = "0.1.0"
authors = ["ashneverdawn <ashneverdawn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [dependencies]
# bevy = "0.4.0"
# bevy_skybox = "0.3.0"
# wasm-bindgen = "0.2.69"
# bevy_webgl2 = { version = "0.4.0", optional=true}
# # bevy_rapier3d = "0.6.2"

# [features]
# web = [
#   "bevy_webgl2"
# ]

[features]
default = [
  "bevy/bevy_gltf",
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png",
]

native = [
  "bevy/bevy_wgpu",
]

web = [
  "bevy_webgl2"
]

[dependencies]
bevy = {version="0.4.0", default-features=false}
libloading = "0.6.7"
# bevy_skybox = "0.3.0"
bevy_webgl2 = {version="0.4.0", optional=true}
winit = {version = "0.24.0"}
uuid = {version="=0.8.1"}
# [patch.'https://github.com/bevyengine/bevy']
# bevy = {git = "https://github.com/bevyengine/bevy//", rev="841755aaf23acfd55b375c37390daeb302c5b30b", default-features=false}

# [patch.'https://github.com/mrk-its/bevy_webgl2']
# bevy_webgl2 = {git = "https://github.com/mrk-its/bevy_webgl2//", rev="035236b8d7ec52b8e9e20399662e89c73e4521f6", default-features=false}

[patch.crates-io]
# libloading = "0.6.7"
# libloading = {git = "https://github.com/nagisa/rust_libloading//", rev = "1cc40888d23607a066164238694f0ccab684555e", features = ["imp"] }

[profile.dev]
opt-level = 1

[profile.release]
# lto = true
# opt-level = 's'

[[example]]
name = "text"
path = "examples/text.rs"
